apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocky-dv-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/rocky
    server: 192.168.0.30
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  claimRef:
    namespace: default
    name: rocky-datavolume