apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocky-datavolume-scratch-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/rocky-scratch
    server: 192.168.0.30
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  claimRef:
    name: rocky-datavolume-scratch
    namespace: default

