apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocky-datavolume-scratch
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc
  volumeName: rocky-datavolume-scratch-pv

